### ISSUE TITLE
编辑器里贴代码如何？

### ISSUE THREAD

**Issue by zjjott** [zjjott/Guokr-extension#42]
需要的元素在http://www.guokr.com/blog/746118/ 有提到
样式可以看看http://www.guokr.com/post/661990/ 的效果

**Comment by ouchxp** [comment]
可以啊, 貌似之前就想过来着 不知为啥没有做...

**Comment by zjjott** [comment]
原因只有一个：懒。。。2333

**Comment by zjjott** [comment]
今天有空，我来做做看~

**Comment by ouchxp** [comment]
好的 你试试吧

**Comment by zjjott** [comment]
https://github.com/zjjott/Guokr-extension/pull/43

卧槽怎么贴进度来着？
